version: "3.8"
services:
  php-apache-environment:
    container_name: med_image
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - ".:/var/www/html"
    ports:
      - 80:80
    networks:
      - med_net

  php:
    image: php:7.4
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/public
    depends_on:
      - database
    networks:
      - med_net

  database:
    container_name: database
    image: mysql:8.0.31
    networks:
      - med_net
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      DB_HOSTNAME: database
      DB_USERNAME: medman
      DB_PASSWORD: password
      DB_DATABASE: med
      DB_ENVIRONMENT: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: med
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: medman
      MYSQL_PASSWORD: password
      PMA_HOST: mysql

    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      DB_HOSTNAME: database
      DB_USERNAME: medman
      DB_PASSWORD: password
      DB_DATABASE: med
      DB_ENVIRONMENT: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: med
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: medman
      MYSQL_PASSWORD: password
      PMA_HOST: database
    networks:
      - med_net

networks:
  med_net:
volumes:
  mysql-data:
